### ISSUE TITLE
possible bug - ip or proxy_ip access in use()

### ISSUE THREAD

**Issue by dougg0k** [kartikk221/hyper-express#117]
Hello,

If I try to access `request.ip` or `request.proxy_ip` in a `use()` middleware. It returns an error. 

The ts type to access them both are there, whoever if I try to `log` the `request` object, both are not there.

```
Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
    at Request.get ip [as ip] (/app/node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/src/components/http/Request.js:819:73)
    at getIP (file:///app/src/helpers/authHelper.ts:37:11)
    at Object.authHandler [as handler] (file:///app/src/handlers/authHandler.ts:16:13)
    at Route.handle (/app/node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/src/components/router/Route.js:92:37)
    at Server._handle_uws_request (/app/node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/src/components/Server.js:381:19)
    at /app/node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/src/components/Server.js:304:26
```

```
Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
    at Request.get proxy_ip [as proxy_ip] (/app/node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/src/components/http/Request.js:835:75)
    at getIP (file:///app/src/helpers/authHelper.ts:36:10)
    at Object.authHandler [as handler] (file:///app/src/handlers/authHandler.ts:16:13)
    at Route.handle (/app/node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/src/components/router/Route.js:92:37)
    at Server._handle_uws_request (/app/node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/src/components/Server.js:381:19)
    at /app/node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/src/components/Server.js:304:26
```

**Comment by kartikk221** [comment]
Hello, this should only occur If the request has actually been closed due to disconnection as only then will `uWS.HttpResponse/SSLHttpResponse` be discarded access. If possible, do you think you can provide a snippet of code around where you consume `request.ip`?

The only way I see this error occuring is in the following manner:
```js
// Assume request was still connected at the beginning of the middleware execution
router.use((request, response, next) => {
    // Perform some async operation
    await something_async();
    // Most likely the request disconnects while the above async operation is still running.

    // Because request is no longer connected, consuming the IP or Proxied IP leads to an access error
   const ip = request.ip; // << This causes the error because the IP is lazy loaded from uWS for performance
   // Some other code here

   next();
});
```

**Comment by dougg0k** [comment]
Yes. 

```
server.use(authHandler);
... other routes
```

```
export function authHandler(
	request: Request,
	response: Response,
	next: MiddlewareNext,
) {
	const authHeader = request.headers["authorization"];
	const authToken = extractToken(authHeader);
	const isAuth = isAuthenticated(authToken);
	if (!isAuth) {
		response
			.status(401)
			.json({ data: null, errors: [{ message: "Unauthorized", code: 401 }] });
	}
	// tried to get request.ip here
	next();
}
```

**Comment by kartikk221** [comment]
I see the issue, you send a 401 response if `isAuth` is falsy but you don't have a return statement. You cannot retrieve ip/proxy_ip data after a response has been sent and the client is no longer connected. Can you try retrieving the ip before the if statement? or you can also just add a return statement in the `response.status().json()` call to prevent the rest of the code from running.

**Comment by dougg0k** [comment]
If I try to add a `return` in the response. I get the following.

```
src/routes.ts:13:13 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(request: Request<DefaultRequestLocals>, response: Response<DefaultResponseLocals>, next: MiddlewareNext) => boolean | undefined' is not assignable to parameter of type 'string'.

13  server.use(authHandler);
               ~~~~~~~~~~~

  node_modules/.pnpm/hyper-express@6.4.7/node_modules/hyper-express/types/components/router/Router.d.ts:51:5
    51     use(pattern: string, ...middlewares: MiddlewareHandler[]): void;
           ~~~
    The last overload is declared here.
```

But you are right, getting the IP before, works. It helped also understand better how hyper-express works.

Thanks for the help.

**Comment by kartikk221** [comment]
Just TypeScript telling you that you aren't allowed to return a string value in a middleware. Instead of using a return, just make your if statement an if/else and contain the rest of the code in the else.

**Comment by dougg0k** [comment]
Right
