### ISSUE TITLE
Websocket client crashes server

### ISSUE THREAD

**Issue by MichaelJCole** [kartikk221/hyper-express#21]
Hi, I'm getting an error when I

1. Start a hyper-express server (repro below)
2. Connect with [WebSocket King Client ](https://websocketking.com/)
3. WAIT 15 seconds or so

The error looks like this, and I think it has something to do with pong.
```
$ ts-node --transpile-only src/index.ts
Webserver started on port 3002
upgrading connection
user some_user_id connected.
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at Function.from (buffer.js:334:9)
    at array_buffer_to_string (/home/michael/casefile-studio/node_modules/hyper-express/src/shared/operators.js:51:19)
    at WebsocketRoute.<anonymous> (/home/michael/casefile-studio/node_modules/hyper-express/src/components/ws/WebsocketRoute.js:42:42)
    at WebsocketRoute._on_pong (/home/michael/casefile-studio/node_modules/hyper-express/src/components/ws/WebsocketRoute.js:157:50)
    at uws_options.pong (/home/michael/casefile-studio/node_modules/hyper-express/src/components/ws/WebsocketRoute.js:116:50)
error Command failed with exit code 1.
```

A minimalish server is this:
```
import HyperExpress from 'hyper-express'

const PORT = 3002
const webserver = new HyperExpress.Server()

async function runServer() {
  // Upgrade HTTP connection to websocket (not always called, can authenticate)
  webserver.upgrade('/ws/connect', async (request, response) => {
    console.log('upgrading connection')
    response.upgrade({
      user_id: 'some_user_id',
    })
  })

  webserver.ws('/ws/connect', async (ws) => {
    console.log('user ' + ws.context.user_id + ' connected.')
  })

  webserver
    .listen(PORT)
    .then((socket) => console.log(`Webserver started on port ${PORT}`))
    .catch((error) => {
      console.error(`Failed to start webserver on port ${PORT}`)
    })
}
```
I'm using node 14.18.1 and these packages:
```
 "dependencies": {
    "hyper-express": "^5.4.0",
    "ts-node": "^9.1.1",
    "typescript": "4"
  },
```

**Comment by kartikk221** [comment]
Good catch, this was occuring due to empty incoming messages for the pong events. I have added empty string defaults internally to prevent the array buffer parser from throwing this error in 5.4.1. See if upgrading to 5.4.1 solves your issue.

**Comment by MichaelJCole** [comment]
Yes!  Awesome project, thank you!
