### ISSUE TITLE
Install hyper-express with PNPM behind a corporate firewall

### ISSUE THREAD

**Issue by cesco69** [kartikk221/hyper-express#276]
Hi, I'm try to install hyper express with [PNPM](https://pnpm.io/) behind corporate firewall.
hyper-express has a github dependencies `uNetworking/uWebSockets` https://github.com/kartikk221/hyper-express/blob/master/package.json#L52, 
I have tried to set proxy on git, but doesn't works:

```
git config --global http.proxy http://172.16.120.119:3128
git config --global https.proxy http://172.16.120.119:3128
git config --global url."https://github.com/".insteadOf git@github.com:
pnpm i hyper-express
```

show this error

```
pnpm i hyper-express
 ERROR  Command failed with exit code 128: git ls-remote --refs git+ssh://git@github.com/uNetworking/uWebSockets.js.git v20.43.0
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

This error happened while installing the dependencies of hyper-express@6.16.3

pnpm: Command failed with exit code 128: git ls-remote --refs git+ssh://git@github.com/uNetworking/uWebSockets.js.git v20.43.0
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (C:\Users\MyName\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.10.5\node_modules\pnpm\dist\pnpm.cjs:24993:17)
    at handlePromise (C:\Users\MyName\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.10.5\node_modules\pnpm\dist\pnpm.cjs:25564:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRepoRefs (C:\Users\MyName\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.10.5\node_modules\pnpm\dist\pnpm.cjs:110529:23)
    at async resolveRef (C:\Users\MyName\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.10.5\node_modules\pnpm\dist\pnpm.cjs:110541:20)
    at async resolveGit (C:\Users\MyName\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.10.5\node_modules\pnpm\dist\pnpm.cjs:110492:24)
    at async Object.resolve (C:\Users\MyName\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.10.5\node_modules\pnpm\dist\pnpm.cjs:110791:173)
    at async run (C:\Users\MyName\AppData\Local\pnpm\global\5\.pnpm\pnpm@8.10.5\node_modules\pnpm\dist\pnpm.cjs:122839:23)
Progress: resolved 1178, reused 1177, downloaded 0, added 0
```

**Comment by kartikk221** [comment]
This seems to be an issue specific to your corporate proxy blocking github resources as uWebsockets.js ships compiled binaries which are downloaded from GitHub assets.

Unfortunately, I wouldn't have any more expertise to provide on this matter other than recommending you try to narrow down the blocking of Github or its subdomains in any way on your corporate proxy.
