### ISSUE TITLE
Application crashes with negotiator when a error is returned in middleware

### ISSUE THREAD

**Issue by BolverBlitz** [kartikk221/hyper-express#329]
I´ve updated from 6.14.12 to 6.17.3.
I return errors in my middleware to validate a request. This causes the application to exit.
```sh
[EBG Web] [14.12.2024 15:55:09] [E] [400] GET "/api/v1/admin_user/count" >> Invalid Token in "middleware\verifyRequest.js:70"
C:\Users\1515\Documents\GitHub\EBG-Webpage\node_modules\hyper-express\src\components\compatibility\ExpressRequest.js:43
        const first = this.#negotiator.mediaType(mimes.filter((type) => typeof type === 'string'));
                           ^

TypeError: Cannot read private member #negotiator from an object whose class did not declare it
    at Request.accepts (C:\Users\1515\Documents\GitHub\EBG-Webpage\node_modules\hyper-express\src\components\compatibility\ExpressRequest.js:43:28)
    at Request.accepts (C:\Users\1515\Documents\GitHub\EBG-Webpage\node_modules\hyper-express\src\components\http\Request.js:950:29)
    at Object.on_error (C:\Users\1515\Documents\GitHub\EBG-Webpage\src\app.js:182:34)
    at Response.throw (C:\Users\1515\Documents\GitHub\EBG-Webpage\node_modules\hyper-express\src\components\http\Response.js:869:33)
    at C:\Users\1515\Documents\GitHub\EBG-Webpage\node_modules\hyper-express\src\components\router\Route.js:123:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.14.0
```

**Comment by BolverBlitz** [comment]
Closing this as i can not write code to reliably produce it
